CUDA_VISIBLE_DEVICES=0 python train_bash.py \
    --stage sft \
    --do_train \
    --model_name_or_path ../models/Qwen2-7B-Instruct/ \
    --dataset chinese_medical \
    --template qwen \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir ./saves/Qwen2-7B-lora/chinese_medical/ \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --save_steps 200 \
    --learning_rate 5e-5 \
    --num_train_epochs 3 \
    --plot_loss
